[package]
name = "eva"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~3.0"
gmi = "0.2.1"
lazy_static = "~1.4"
fastrand = "~1.7"
toml = "~0.5"
gemview = { git = "https://codeberg.org/jeang3nie/gemview" }

[dependencies.gtk]
version = "~0.4"
package = "gtk4"

[dependencies.rgba_simple]
version = "~0.5"
features = ["gdk"]

[dependencies.serde]
version = "~1.0"
features = ["derive"]
