[package]
name = "eva"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "~0.2"
gmi = { git = "https://gitlab.com/jeang3nie/gmi.git" }
lazy_static = "~1.4"
fastrand = "~1.7"
toml = "~0.5"
gemview = { git = "https://codeberg.org/jeang3nie/gemview" }

[dependencies.chrono]
version = "~0.4"
features = ["std"]

[dependencies.gtk]
version = "~0.4"
package = "gtk4"

[dependencies.rgba_simple]
version = "~0.5"
features = ["gdk"]

[dependencies.serde]
version = "~1.0"
features = ["derive"]

[profile.release]
panic = 'abort'
lto = true
codegen-units = 1
